- hosts: all
  gather_facts: no
  tags: dependency
  tasks:
    - name: wait for port 22 to be ready
      sudo: no
      local_action: wait_for port=22 host="{{ inventory_hostname }}"  
    - name: install python
      sudo: yes
      raw: apt-get install -y python
      
- hosts: node
  roles:
    - role: flu

