# - name: add PPAs
#   apt_repository: repo={{ item }}
#   with_items:
#     - "ppa:ethereum/ethereum-qt"
#     - "ppa:ethereum/ethereum"
#     - "ppa:ethereum/ethereum-dev"

# - name: update apt
#   apt: update_cache=yes

# - name: install flu
#   apt: state=present pkg=flu
#   tags:
#     - update

# - name: create fluidity dir
#   file: path={{ base_dir }}/.fluidity state=directory

- name: open 40404 for UDP
  ufw: rule=allow port=40404 proto=udp
  notify: reload ufw

- name: copy flu configs over
  template: src=flu-config.json dest="{{flu_config_path}}"

- name: open the rpc port
  when: "'rpc' in group_names"
  ufw: rule=allow port=8545 proto=tcp
  notify: reload ufw

- name: start the flu docker container
  docker:
    state: reloaded
    name: flu
    image: jesuscript/flu
    pull: always
    command: /usr/bin/flu --jsonrpc --jsonrpc-cors-domain '*' --config /flu/.flu.json "{{ '--start-sealing' if 'validator' in group_names else '' }}"
    volumes:
      - "{{flu_config_path}}:/flu/.flu.json"
    ports:
      - "8545:8545"
      - "40404:40404/udp"
  tags: test
