- name: get enode ID
  shell: docker logs flu 2>&1 | grep -m1 -oP '(Node ID:)([^\@])*' | awk '{print $3}'
  register: v_enode
  until: v_enode.stdout != ""
  retries: 20
  delay: 1

- name: get account address
  shell: curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://localhost:8545 
  register: v_accounts_res
  when: "'signer' in group_names"

- name: save address as a fact
  set_fact:
    address: "{{ (v_accounts_res.stdout|from_json).result[0] }}"
  when: "'signer' in group_names"

- name: save enode as a fact
  set_fact: enode={{v_enode.stdout}}

- name: copy flu configs over
  template: src=flu-config.json dest="{{flu_config_path}}"
  notify: restart flu



 