#!/bin/bash

node cloud_shepard/digital_ocean.js create -p $DO_KEY -s group_vars/sshkeys/key.pub -c config/do-full.json -w group_vars/inventory/do_auto

export ANSIBLE_HOST_KEY_CHECKING=False

ansible-playbook install-python.yml -v -i group_vars/inventory/do_auto
ansible-playbook flu-node.yml -v -i group_vars/inventory/do_auto
ansible-playbook flu-network.yml -v -i group_vars/inventory/do_auto
ansible-playbook stats.yml -v -i group_vars/inventory/do_auto
